[workspace]
# members = ["node", "hbbft-abci", "evm-abci"]
members = ["hbbft-abci", "evm-abci"]

# TODO: Remove once new revm release
[patch.crates-io]
revm = { git = "https://github.com/bluealloy/revm", package = "revm"  }
